name: Check Requirements Up to Date

on:
  push:
    paths:
      - 'requirements.txt'
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install pip-review
        run: |
          python -m pip install --upgrade pip
          pip install pip-review
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check for outdated packages
        run: |
          OUTDATED=$(pip-review --local --raw)
          if [ -n "$OUTDATED" ]; then
            echo "❌ The following packages are outdated:"
            echo "$OUTDATED"
            exit 1
          else
            echo "✅ All packages are up to date."
          fi
