name: Check Requirements Up to Date

on:
  push:
    paths:
      - 'requirements.txt'
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install pip-review
        run: |
          python -m pip install --upgrade pip
          pip install pip-review
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check for outdated packages
        run: |
            # Extract only the package names (no version pins)
            REQ_PACKAGES=$(grep -oP '^[a-zA-Z0-9\-_]+' requirements.txt)

            # Check for outdated packages and capture their names
            OUTDATED=$(pip list --outdated --format=freeze | cut -d= -f1)

            # Find intersection between the two
            OUTDATED_MATCHED=""
            for pkg in $REQ_PACKAGES; do
              if echo "$OUTDATED" | grep -iq "^$pkg$"; then
                OUTDATED_MATCHED+="$pkg"$'\n'
              fi
            done

            if [ -n "$OUTDATED_MATCHED" ]; then
              echo "❌ The following packages from requirements.txt are outdated:"
              echo "$OUTDATED_MATCHED"
              exit 1
            else
              echo "✅ All packages in requirements.txt are up to date."
            fi
